services:
  - type: web
    name: ecomerce-app
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: PORT
        value: 3005
      - key: DATABASE_URL
        sync: false
      - key: SECRET_KEY
        generateValue: true
